homes/urls.py
from django.conf.urls import url
from homes.views import HomeDetail, HomeSearchListView

urlpatterns = [

    url(r'^property-listing/$', HomeSearchListView.as_view
        (template_name='property-listing.html'), name='list'),
    url(r'^property-listing/(?P<home_id>[0-9]+)/like', 'homes.views.home_like',
        name='likes'),
    url(r'^property-listing/(?P<home_id>[0-9]+)/dislike',
        'homes.views.home_dislike', name='dislikes'),
    url(r'^user-account/(?P<user_id>[0-9]+)', 'homes.views.profile_view',
        name='profile'),
    url(r'^likes/(?P<user_id>[0-9]+)',
        'homes.views.profile_view_likes', name='userlikes'),
    url(r'^dislikes/(?P<user_id>[0-9]+)', 'homes.views.profile_view_dislikes',
        name='userdislikes'),
    url(r'^(?P<home_id>[0-9]+)/', HomeDetail.as_view(), name="detail"),

]

perfect_home/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from homes.views import HomeList

urlpatterns = [

    url(r'^register', 'homes.views.create_user', name='user_reg'),
    url(r'^login', auth_views.login, {'extra_context': {'next': '/'}},
        name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^homes/', include('homes.urls')),
    url(r'^$', HomeList.as_view(), name='index'),
]

homes/models.py
from django.db import models
from django.contrib.auth.models import User


class Home(models.Model):
    """
    model for creating a Home object.

    """
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=20)
    zipcode = models.CharField(max_length=10)
    bedrooms = models.CharField(max_length=50, null=True, blank=True)
    bathrooms = models.CharField(max_length=100)
    sqft = models.CharField(max_length=12, null=True, blank=True)
    lot_size = models.CharField(max_length=50, blank=True)
    year_built = models.CharField(max_length=5, null=True, blank=True)
    price = models.CharField(max_length=50, null=True)
    price_per_sqft = models.CharField(max_length=10, null=True, blank=True)
    img = models.CharField(max_length=500, null=True, blank=True)
    user = models.ManyToManyField(User)

    def __str__(self):
        return ("Address:{}, City: {}, State {}, Zipcode {},"
                "Bedrooms: {}, Bathrooms: {}, Sqft: {}, "
                "Lot Size: {}, Year Built: {}, Price: {}, "
                "Price Per Sqft: {}, Img: {}".format(self.address, self.city,
                                                     self.state, self.zipcode,
                                                     self.bedrooms,
                                                     self.bathrooms, self.sqft,
                                                     self.lot_size,
                                                     self.year_built,
                                                     self.price,
                                                     self.price_per_sqft,
                                                     self.img))


class Customer(models.Model):
    """
    model for creating a Customer/User object

    """
    user = models.OneToOneField(User)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return ("User: {}, "
                "First Name: {}, "
                "Last Name: {}, "
                "Email: {}".format(self.user, self.first_name,
                                   self.last_name, self.email))


class Like(models.Model):
    """
    model for creating a liked Home by a User

    """
    user = models.ForeignKey(Customer)
    home = models.ForeignKey(Home)

    def __str__(self):
        return "User: {} Home: {}".format(self.user, self.home)


class Dislike(models.Model):
    """
    model for creating a disliked Home by a User

    """
    user = models.ForeignKey(Customer)
    home = models.ForeignKey(Home)

    def __str__(self):
        return "User: {}, Home: {}".format(self.user, self.home)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Perfect Home - The Next Generation of Property Listing">
	<meta name="author" content="Zul Azman">
	
	<link rel="shortcut icon" type="image/ico" href={% static "img/favicon.ico"%}>
	<link rel="apple-touch-icon" href="http://zulazman.com/#">
	<link rel="apple-touch-icon" sizes="144x144" href="#">
	<link rel="apple-touch-icon" sizes="114x114" href="#">

	<link rel="stylesheet" type="text/css" href={% static "bootstrap/css/bootstrap.css" media="screen"%}>
	<link rel="stylesheet" type="text/css" href={% static "css/font-awesome/css/font-awesome.min.css" media="screen"%}>
	<link rel="stylesheet" type="text/css" href={% static "css/style.css" media="screen"%}>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  	<script>window.jQuery || document.write('<script src="js/library/jquery/jquery.min.js">\x3C/script>')</script>

  	<!-- Maplace.js -->
	<script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"></script>
	<script src={% static "js/lib/maplace.js"%}></script>
	<script src={% static "js/custom.map.js"%}></script>

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	<title>Perfect Home - The Next Generation of Property Listing</title>

</head>

<body>

<div class="site-wrapper">
	<div class="site-row row-offcanvas row-offcanvas-left">
		<section id="header">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav class="navbar navbar-default" role="navigation">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header">
								<button type="button" class="hidden-md hidden-lg navbar-toggle navbar-search-toggle" data-toggle="offcanvas">
									<span class="sr-only">Toggle Search</span>
									<i class="fa fa-search"></i>
									<i class="fa fa-times"></i>
								</button>

								<a class="current navbar-brand" href={% url 'index' %}>Perfect Home</a>
								
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
									<span class="sr-only">Toggle Navigation</span>
									<i class="fa fa-bars"></i>
								</button>
							</div>

							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse" id="collapse">
								
								<ul class="nav navbar-nav navbar-right">
									<li class="dropdown">
									</li>
                                    {% if user.is_authenticated %}
									<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="caret"></b></a>
										<ul class="dropdown-menu">
											<li><a href={% url 'profile' user.pk %}>User Profile</a></li>
										</ul>
                                    {% else %}
                                    <ul></ul>
									</li>
                                    {% endif %}
                                    {% if not user.is_authenticated %}
									<li><a href="#modal-login" class="login" data-toggle="modal" data-target="#modal-login">Log In</a></li>
									<li><a href="#modal-register" class="register" data-toggle="modal" data-target="#modal-register">Register</a></li>
                                    {% else %}

                                        <li><a href="{% url 'logout' %}" class="register">Logout</a></li>
                                    {% endif %}
								</ul>

							</div><!-- /.navbar-collapse -->
						</nav>
					</div>
				</div>
			</div>
		</section>
    {% block content %}
    {% endblock %}

<section id="connect">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter clearfix">
							<div class="col-md-2 col-sm-12">
								<h5>Keep in Touch!</h5>
							</div>
							<div class="col-md-7 col-sm-9">
								<form class="form-inline normal-form">
									<div class="form-group">
										<input type="text" class="form-control" id="" placeholder="Your Name">
									</div>

									<div class="form-group">
										<input type="email" class="form-control" id="" placeholder="Your Email">
									</div>

									<button type="submit" class="btn btn-flat-alizarin">Subscribe to our Newsletter!</button>
								</form>
							</div>
							<div class="col-md-3 col-sm-3">
								<ul class="social-media list-unstyled clearfix">
									<li><a class="linkedin" href="#" data-toggle="tooltip" data-placement="top" title="Follow us on Linkedin!"><i class="fa fa-linkedin"></i></a></li>
									<li><a class="facebook" href="#" data-toggle="tooltip" data-placement="top" title="Like us on Facebook!"><i class="fa fa-facebook"></i></a></li>
									<li><a class="twitter" href="#" data-toggle="tooltip" data-placement="top" title="Follow us on Twitter!"><i class="fa fa-twitter"></i></a></li>
									<li><a class="google" href="#" data-toggle="tooltip" data-placement="top" title="Add on Google+!"><i class="fa fa-google-plus"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section id="footer">
		</section>

		<section id="footer-bottom">

			<div class="container">
				<div class="row">
					<div class="inner-column clearfix">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p class="text-left">
							 	Data on sold prices provided by Awesome Land Registrar of Country.
							</p>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p class="text-right">
							 	&copy; 2015 zRealty Ptd. Ltd. All rights reserved.
							</p>
						</div>
					</div>
				</div>
			</div>

		</section>


	<!-- Modal Login -->
	<div class="modal modal-login fade" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="modalLogin" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

					<h4 class="modal-title" id="modalLogin">Log In</h4>
				</div>
				<div class="modal-body">
					<form class="normal-form" role="form" method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="/">
						<div class="form-group">
							<label for="" class="sr-only">Email</label>
							<input type="text" class="form-control" id="" placeholder="Username" name="username">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">Password</label>
							<input type="password" class="form-control" id="" placeholder="Password" name="password">
						</div>

						<div class="form-group">
							<a href="#modal-recover" data-dismiss="modal" data-toggle="modal" data-target="#modal-recover">Forgot Password?</a>
						</div>
                        <div class="modal-footer">
					<a href="#modal-register" data-dismiss="modal" data-toggle="modal" data-target="#modal-register">I do not have an account. Register here.</a>
					<button type="submit" value="login" class="btn-credential btn btn-flat-alizarin btn-block">Log In</button>
				</div>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

	<!-- Modal Register -->
	<div class="modal modal-register fade" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="modalRegister" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="modalRegister">Register</h4>
				</div>
				<div class="modal-body">
					<form class="normal-form" role="form" method="post" action="{% url 'user_reg' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="/">
						<div class="form-group">
							<label for="" class="sr-only">Username</label>
							<input type="text" class="form-control" id="" placeholder="Username" name="username">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">First Name</label>
							<input type="text" class="form-control" id="" placeholder="First Name" name="first_name">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">Last Name</label>
							<input type="text" class="form-control" id="" placeholder="Last Name" name="last_name">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">Email</label>
							<input type="email" class="form-control" id="" placeholder="Email" name="email">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">Password</label>
							<input type="password" class="form-control" id="" placeholder="Password" name="password1">
						</div>

						<div class="form-group">
							<label for="" class="sr-only">Password</label>
							<input type="password" class="form-control" id="" placeholder="Confirm Password" name="password2">
						</div>
					    <a href="#modal-login" data-dismiss="modal" data-toggle="modal" data-target="#modal-login">Already have an account? Log in here</a>
                        <button type="submit" value="Register" class="btn-credential btn btn-flat-alizarin btn-block">Register</button>
					</form>
				</div>
				<div class="modal-footer">
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

	<!-- Modal Recover -->
	<div class="modal modal-recover fade" id="modal-recover" tabindex="-1" role="dialog" aria-labelledby="modalRecover" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="modalRecover">Recover Password</h4>
				</div>
				<div class="modal-body">
					<form class="normal-form" role="form">
						<div class="form-group">
							<label for="" class="sr-only">Email</label>
							<input type="email" class="form-control" id="" placeholder="Enter email">
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<span>Enter email above to recover password.</span>
					<button type="button" class="btn-credential btn btn-flat-alizarin btn-block">Submit</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->


	</div><!-- end .site-row -->
</div><!-- end .site-wrapper -->

<!-- Utilities -->
<script src={% static "bootstrap/js/bootstrap.min.js" type="text/javascript"%}></script>
<script src={% static "js/modernizr-latest.js" type="text/javascript"%}></script>

<!-- JQuery Thumbscubber - iPhoto Thumbnail -->
<script src={% static "js/lib/thumbscrubber.js" type="text/javascript"%}></script>

<!-- JQuery Filmstrip -->
<script src={% static "js/lib/jquery.filmstrip.js" type="text/javascript"%}></script>

<!-- Bootstrap Select -->
<script src={% static "js/lib/bootstrap-select/bootstrap-select.min.js" type="text/javascript"%}></script>

<!-- Bootstrap Checkbox -->
<script src={% static "js/lib/bootstrap-checkbox.js" type="text/javascript"%}></script>

<!-- Bootstrap File Input -->
<script src={% static "js/lib/bootstrap-fileinput.js" type="text/javascript"%}></script>

<!-- Bootstrap Tags Input -->
<script src={% static "js/lib/bootstrap-tagsinput/bootstrap-tagsinput.min.js" type="text/javascript"%}></script>

<!-- Custom JS for zRealty -->
<script src={% static "js/custom.style.js" type="text/javascript"%}></script>

<script>
 function setEqualHeight(selector, triggerOnInput) {
    	var elements = $(selector)
    	elements.css("height", "auto")
    	var max = Number.NEGATIVE_INFINITY;
    	$.each(elements, function(index, item) {
    		if ($(item).height() > max) {
    			max = $(item).height()
    		}
    	})
    	$(selector).css("height", max + "px")

    	if (!!triggerOnInput) {
    		$(document).on("input", selector, function() {
    			setEqualHeight(selector, false)

    		})
    	}

    	$(window).resize(function() {
    		setEqualHeight(selector, false)
    	})
    }

        setEqualHeight(".sameh", true)
</script>

</body>

</html>

templates/homedetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/user-account-dislike.html
{% extends "base.html" %}
{% load staticfiles %}
{% load humanize %}
{% block content %}

<div class="site-wrapper">
	<div class="site-row row-offcanvas row-offcanvas-left">

<section id="profile-info">

	<div class="profile-cover-section">
		<div class="title-section-img">
			<img src={% static "img/img-coverphoto.jpg" style="top: -380px;"%}/>
		</div>
	</div>

	<div class="profile-cover-info"></div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-profile">
					<span class="sr-only">Toggle Navigation</span>
					<i class="fa fa-ellipsis-h"></i>
				</button>
				<button type="button" class="btn btn-icon hidden-md hidden-lg text-left" data-toggle="offcanvas-sm">
					<i class="fa fa-user"></i>
				</button>
				<div class="clearfix"></div>
				<div class="collapse navbar-collapse" id="collapse-profile">
					<ul id="profiletab" class="nav nav-tabs nav-tabs-hollo">
						<li><a href="{% url 'profile' user.pk %}">Overview</a></li>
                        <li><a href="{% url 'userlikes' user.pk %}">Liked</a></li>
                        <li class="current active"><a class='current' href="{% url 'userdislikes' user.pk %}">Disliked</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

</section>

<section id="content">
	<div class="container overflow-hidden">
		<div class="row row-offcanvas row-offcanvas-left row-offcanvas-sm row-offcanvas-sm-left row-offcanvas-xs box-padding">
			<div class="col-md-3 sidebar-offcanvas sidebar-offcanvas-sm">

			</div>
			<div class="col-md-9">
				<div class="profile-content">
	<div class="tab-content no-bg no-border">
	</div>
			</div>

		</div>

		<!-- Listing Rent -->
		<div class="product-list grid-layout clearfix">
			<div class="row">
				<div class="col-sm-12 col-md-12 the-title text-left">
					<div class="row">
						<div class="col-md-7 col-sm-7 col-xs-8">
							<h3>Homes you recently Disliked!</h3>
							<span></span>
						</div>
						<div class="col-md-5 col-sm-5 col-xs-4">
						</div>
					</div>
				</div>
                {% for dislike in dislike_list %}
				<div class="prop-item col-sm-6 col-md-4">
					<div class="thumbnail">
						<div class="thumbnail-img thumbscrubber">
						    <span class="ts-inner">

<img src="{{ dislike.home.img }}" alt="House" class="ts-currslide">


						    </span>
						</div>

						<div class="thumbnail-body">
							<div class="caption">
								<a href={% url 'detail' dislike.home.id %}>
									<h3><span class="prop-address">{{ dislike.home.address }}<br>{{ dislike.home.city }}, {{ dislike.home.state }}. {{ dislike.home.zipcode }}</span></h3>
									<div class="prop-price">${{ dislike.home.price|intcomma}}<span></span></div>
								</a>
							</div>

							<div class="content clearfix">
								<ul class="list-unstyled feature-list">
                                <li>{{ dislike.home.bedrooms }} Bedrooms</li>
								<li>{{ dislike.home.bathrooms }} Baths</li>
								<li>{{ dislike.home.sqft }} ft <sup>2</sup></li>
								</ul>

								<div class="link-action clearfix">
								</div>
							</div>
						</div>

					</div>
				</div>
                {% endfor %}
	</div>
			</div>

		</div>

					</div>
				</div>

					</div>
				</div>

					</div>
        </div>
			</div>
{% endblock %}

templates/user-account-like.html
{% extends "base.html" %}
{% load staticfiles %}
{% load humanize %}
{% block content %}

<div class="site-wrapper">
	<div class="site-row row-offcanvas row-offcanvas-left">

<section id="profile-info">

	<div class="profile-cover-section">
		<div class="title-section-img">
			<img src={% static "img/img-coverphoto.jpg" style="top: -380px;"%}/>
		</div>
	</div>

	<div class="profile-cover-info"></div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-profile">
					<span class="sr-only">Toggle Navigation</span>
					<i class="fa fa-ellipsis-h"></i>
				</button>
				<button type="button" class="btn btn-icon hidden-md hidden-lg text-left" data-toggle="offcanvas-sm">
					<i class="fa fa-user"></i>
				</button>
				<div class="clearfix"></div>
				<div class="collapse navbar-collapse" id="collapse-profile">
					<ul id="profiletab" class="nav nav-tabs nav-tabs-hollo">
						<li><a href="{% url 'profile' user.pk %}">Overview</a></li>
                        <li class="current active"><a class="current" href="{% url 'userlikes' user.pk %}">Liked</a></li>
                        <li><a href="{% url 'userdislikes' user.pk %}">Disliked</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

</section>

<section id="content">
	<div class="container overflow-hidden">
		<div class="row row-offcanvas row-offcanvas-left row-offcanvas-sm row-offcanvas-sm-left row-offcanvas-xs box-padding">
			<div class="col-md-3 sidebar-offcanvas sidebar-offcanvas-sm">

			</div>
			<div class="col-md-9">
				<div class="profile-content">
	<div class="tab-content no-bg no-border">

		<!-- Listing Sale -->
		<div class="product-list grid-layout clearfix">
			<div class="row">
				<div class="col-sm-12 col-md-12 the-title text-left">
					<div class="row">
						<div class="col-md-7 col-sm-7 col-xs-8">
							<h3>Homes you recently Liked!</h3>
							<span></span>
						</div>
						<div class="col-md-5 col-sm-5 col-xs-4">
						</div>
					</div>
				</div>
                {% for like in like_list %}
				<div class="prop-item col-sm-6 col-md-4">
					<div class="thumbnail">
						<div class="thumbnail-img thumbscrubber">
						    <span class="ts-inner">

<img src="{{ like.home.img }}" alt="House" class="ts-currslide">
{#<img src="http://upload.wikimedia.org/wikipedia/commons/7/75/Family-room-700.jpg" alt="Family Room">#}
{#<img src="http://upload.wikimedia.org/wikipedia/commons/3/39/METLA_SUIHKU_big.jpg" alt="Bathroom">#}
{#<img src="http://upload.wikimedia.org/wikipedia/commons/b/b2/Fully_Furnished_Atenas_Apartments_for_rent.jpg" alt="Kitchen">#}
						    </span>
						</div>

						<div class="thumbnail-body">
							<div class="caption">
								<a href={% url 'detail' like.home.id %}>
									<h3><span class="prop-address">{{ like.home.address }}<br>{{ like.home.city }}, {{ like.home.state }}. {{ like.home.zipcode }}</span></h3>
									<div class="prop-price">${{ like.home.price|intcomma}}<span></span></div>
								</a>
							</div>

							<div class="content clearfix">
								<ul class="list-unstyled feature-list">
                                <li>{{ like.home.bedrooms }} Bedrooms</li>
								<li>{{ like.home.bathrooms }} Baths</li>
								<li>{{ like.home.sqft }} ft <sup>2</sup></li>
								</ul>
							</div>
						</div>

					</div>
				</div>
                {% endfor %}
	</div>
			</div>

		</div>
	</div>
			</div>

		</div>

					</div>
				</div>

					</div>
				</div>

					</div>
        </div>
			</div>
{% endblock %}